#application.properties? ??
#serport.post=8081
#spring.datasource.url = jdbc:mariadb://localhsot:3306/member
#spring.datasource.username=root
#spring.datasource.password=1234

#
#server:
#    port:8081

#spring:
##   Controller와 jsp사용시에 경로와  확장자 설정
##    기본설정이 타임리프이미르 라임리프 의존성 제거해야 jsap사옹가능
#
#    mvc:
#     view:xd
#        prefix:/WEB-INF/views/
#        suffix:.jsp
#    profiles:
#        active = prod
spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/basic
        username: root
        password: 1234
    jpa:
        database: mysql
#        innoDB ???? ??
        database-platform: org.hibernate.dialect.MariaDBDialect
#        ???? ???? ??
        generate-ddl: true
        hibernate :
#            create??? ?? table? drop? ??
#            update??? ????? alter? ??
#            validate? ??DB?? ???? check
#            ????? update ?? validate ??
         ddl-auto: update
#            jpa? ???? ??? ????. ??? console?? ?????
        show_sql: true
# springboot2.4이상에서는 기본적으로 pathPatternparser를 사용하고 있는데,
#이는 이전버전과 다른 경로매칭규칙을 가지고 있어, springfox와 같은 일부라이브러리에서는 문제 발생
    mvc:
      pathmatch:
          matching-strategy: ant_path_matcher

#mybatis:
#    mapper-locations: classpath:/mapper/**/*.xml