# 워크플로우의 이름을 지정
name: Deploy to AWS_S3

# push 이벤트 지정
# main 브랜치에 push 될때마다 워크플로우가 실행되도록 지정
on:
  push:
    branches:
      - main

jobs:
  # 작업의 이름 지정
  build-and-deploy:
    # 가상 OS 공간
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup node.js
        uses: action/setup-node@v2
        with:
          node version: '20'

      - name: npm install
        run: npm install

      - name: npm build
        run: npm build

      - name: setup aws cli
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_S3_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_S3_SECRET_KEY}}
          aws-region: "ap-northeast-2"


      - name: deploy to s3
        run: |
          aws s3 cp ./dist s3://ordersystem-vue/ --recursive